### ISSUE TITLE
新規データ

### ISSUE THREAD

**Issue by inuflu** [naka345/madplot#20]
ws-1, 2, 3のデータから、添付のような図を作ることができるはず。

[ws-1.txt](https://github.com/naka345/madplot/files/5067389/ws-1.txt)
[ws-2.txt](https://github.com/naka345/madplot/files/5067390/ws-2.txt)
[ws-3.txt](https://github.com/naka345/madplot/files/5067391/ws-3.txt)
![ws-figure](https://user-images.githubusercontent.com/69202112/90100581-f6d19b00-dd77-11ea-9332-fbd4944e2600.png)

**Comment by naka345** [comment]
@inuflu 
exelで出した時の標準誤差の値、txtファイルでもいいから出せたりする？

ちなみにこっちの出力結果。整数になるように丸め込んでる。
||0|12|24|36|48|60|
|:--:|:--:|:--:|:--:|:--:|:--:|:--:|
|item1|0|48381|16996731|49216076|28803291|23720595|
|item2|2|438|70919|34722177|39534326|14142135|
|item3|0|20548|23726840|18856180|13608276|2721655|
|item4|0|31|1085|4189|2841|4064|
|item5|2|19|427|3474|6364|8721|

**Comment by naka345** [comment]
@inuflu
![same_input_filename](https://user-images.githubusercontent.com/12771754/90332241-3d342d80-dff6-11ea-9768-16ca11d76289.png)
尺の問題かなぁ...

**Comment by inuflu** [comment]
不偏標準偏差というのを使ってくれ。
numpy.std(data, ddof=1)で計算してくれるはず。
[ws-不偏標準偏差.txt](https://github.com/naka345/madplot/files/5080602/ws-.txt)

**Comment by naka345** [comment]
標準偏差？
標準誤差じゃなかったっけ・・・
偏差を標本数の平方根で割る
`numpy.std(data, ddof=False) / math.sqrt(len(data))`
不偏標準偏差から誤差も出せるっちゃ出せるけど...

**Comment by naka345** [comment]
@inuflu 
![same_input_filename](https://user-images.githubusercontent.com/12771754/90590521-b82a5d80-e21b-11ea-9c80-995c88223f68.png)

変更した
そっちでも動くかどうか
```
git checkout develop
git checkout -b average
git pull origin average
```
で差分落として確認してみて
